# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn StateCU (for Software Developers)
pages:
- Home: index.md
- 'Development Environment':
  - 'Overview': dev-env/overview.md
  - 'Machine': dev-env/machine.md
  - 'Git': dev-env/git.md
  - 'Python and pip': dev-env/python.md
  - 'Pytest': dev-env/pytest.md
  - 'MkDocs': dev-env/mkdocs.md
  - 'Java 8': dev-env/java8.md
  - 'gfortran': dev-env/gfortran.md
  - 'Eclipse and Photran': dev-env/eclipse.md
  - 'Doxygen': dev-env/doxygen.md
  - 'KDiff3': dev-env/kdiff3.md
- 'Initial Project Setup':
  - Overview: project-init/overview.md
  - 'Create Development Home Folder': project-init/home-folder.md
  - 'Create GitHub Repository': project-init/github.md
  - 'Eclipse Run Script': project-init/eclipse-run-script.md
  - 'Eclipse Workspace': project-init/eclipse-workspace.md
  - 'Eclipse StateCU Project': project-init/eclipse-statecu-project.md
  - 'Eclipse Folder Structure': project-init/eclipse-folder-structure.md
  - 'Eclipse Make Targets': project-init/eclipse-make-targets.md
  - 'Build Utility Scripts': project-init/build-util.md
  - 'Documentation, Developer (MkDocs)': project-init/doc-dev.md
  - 'Documentation, User (MkDocs)': project-init/doc-user.md
  - 'Documentation, API (Doxygen)': project-init/doc-doxygen.md
- 'Deployed Environment':
  - 'Overview': deployed-env/overview.md
- 'New Developer':
  - 'Overview': dev-new/overview.md
- 'Software Design':
  - 'Overview': software-design/overview.md
- 'Development Tasks':
  - 'Overview': dev-tasks/overview.md
  - 'Run Eclipse': dev-tasks/run-eclipse.md
  - 'Designing Software': dev-tasks/designing-software.md
  - 'Version Control with Git': dev-tasks/versioning.md
  - 'Documenting': dev-tasks/documenting.md
  - 'Troubleshooting Eclipse': dev-tasks/troubleshooting-eclipse.md
  - 'Compiling': dev-tasks/compiling.md
  - 'Testing': dev-tasks/testing.md
  - 'Deploying': dev-tasks/deploying.md
  - 'FAQ for Cygwin': dev-tasks/faq-cygwin.md
  - 'FAQ for Linux': dev-tasks/faq-linux.md
  - 'FAQ for MinGW': dev-tasks/faq-mingw.md
theme: readthedocs
repo_url:  https://github.com/OpenWaterFoundation/owf-learn-cdss-statecu-dev
site_description:  Colorado's Decision Support Systems StateCU software developer documentation
site_author:  Open Water Foundation
site_favicon:  StateCU-favicon.png
#copyright:  Copyright Open Water Foundation
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
